version: "3.8"
services:
  api:
    image: bitnami/prometheus
    ports:
      - "9090:9090"
    networks:
      - metric-net
    deploy:
      mode: replicated
      replicas: 1
      labels: 
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 10s
networks:
  metric-net:
    driver: overlay
    attachable: true
volumes:
  prometheus:
    external: true